### PR TITLE
property to set Monday as first day of week

### PR DESCRIPTION
**Pull request by jjoe64**

### CODE REVIEW

**Comment by glad** [comment]
This will be available in the next update.  Thanks for the suggestion.

**Comment by wirn** [comment]
Any progress with this?
I implemented glDatePicker and think its great but needs to change to another calender if Im not able to set Monday as the first day....

**Comment by glad** [comment]
Hi Wirn,

Terribly sorry about this however glDatePicker underwent a rewrite a short while back so I will be incorporating this feature (and then some).

Unfortunately I don't have an exact date on the new version's release but I am hoping it is before this year ends.

**Comment by glad** [comment]
Duplicate of this issue:
https://github.com/glad/glDatePicker/pull/3

**Pull request closed without merging**
